# Generated by Django 3.2 on 2021-07-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='is_active',
        ),
    ]
